title: Boilerplate
description: Boilerplate is a Hexo boilerplate theme for building static pages themed by Bulma UI framework.
author: Ricky Hurtado
theme: boilerplate
source_dir: source
public_dir: static
permalink: /archives/:title/
