#!/bin/bash
source $PWD/bin/bash.sh

GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

echo 'Installing node modules...'
yarn install
yarn global add gulp hexo
echo ''

echo 'Compiling scss files...'
gulp compile-sass --silent
echo -e "${GREEN}success${NC} Compiled to \"styles.css\""
echo -e "${GREEN}success${NC} Minified to \"styles.min.css\""
echo ''

echo 'Transpiling js files...'
gulp transpile-js --silent
echo -e "${GREEN}success${NC} Transpiled to \"app.js\""
echo -e "${GREEN}success${NC} Uglified to \"app.min.js\""
echo ''

echo 'Building static files...'
hexo generate --silent
rm static/css/styles.css
rm -rf static/archives
echo -e "${GREEN}success${NC} Build completed."
echo ''

echo -e "${BLUE}======================================================${NC}"
echo -e "${BLUE}Run server: hexo server -p 7777${NC}"
echo ''
echo -e "${BLUE}Visit https://hexo.io for documentation.${NC}"
echo -e "${BLUE}Visit https://bulma.io for documentation.${NC}"
echo ''
echo -e "${BLUE}https://github.com/rickyhurtado/hexo-boilerplate-theme${NC}"
echo -e "${BLUE}https://facebook.com/Ironcoder${NC}"
echo -e "${BLUE}https://instagram.com/i.am.ironcoder${NC}"
echo ''
echo -e "${BLUE}JOHN 3:16 #TrainAndWitness #RaceAndWitness LUKE 9:23${NC}"
echo -e "${BLUE}======================================================${NC}"
